import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { ViewTransitions } from "next-view-transitions";
import SmoothScroll from "./components/SmoothScroll";
import Footer from "./components/Footer";
import Script from "next/script";
import LockVh from "./components/LockVh";
const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <head>
          {/* 1) Calendly widget */}
          <Script
            src="https://assets.calendly.com/assets/external/widget.js"
            strategy="afterInteractive"
          />
        </head>
        <body
          className={`antialiased funnel-display w-screen overflow-x-hidden bg-white`}
        >
          <LockVh />
          <NavBar />
          <SmoothScroll />
          {children}
          <Footer />
        </body>
      </html>
    </ViewTransitions>
  );
}
