import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { ViewTransitions } from "next-view-transitions";
import SmoothScroll from "./components/SmoothScroll";
const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`antialiased font-sans w-screen overflow-x-hidden bg-black`}
        >
          <NavBar />
          <SmoothScroll />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
